version: '3'

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - "3000:5000"
    environment:
      - PORT=3000
      - ACCESS_TOKEN_SECRET=acsec
      - REFRESH_TOKEN_SECRET=refsec
      - VERIFY_TOKEN_SECRET=versec
      - EMAIL_ADDRESS=soheilaminlo80@gmail.com
      - EMAIL_PASSWORD=SOHEIL123HNJ
      - MONGO_URL=mongodb://mongo_db:27017/Accomodation
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}